import type { CableRoute, PlannerItem } from "./types";

export const INITIAL_ITEMS: PlannerItem[] = [
  {
    id: "frame-top",
    kind: "obstacle",
    name: "Rear frame",
    x: 126,
    y: 76,
    width: 1348,
    height: 64,
    rotation: 0,
  },
  {
    id: "frame-left",
    kind: "obstacle",
    name: "Left frame",
    x: 126,
    y: 76,
    width: 64,
    height: 250,
    rotation: 0,
  },
  {
    id: "frame-right",
    kind: "obstacle",
    name: "Right frame",
    x: 1410,
    y: 76,
    width: 64,
    height: 250,
    rotation: 0,
  },
  {
    id: "power-strip",
    kind: "power-brick",
    name: "6-outlet power strip",
    x: 590,
    y: 174,
    width: 420,
    height: 80,
    rotation: 0,
    outlets: 6,
  },
  {
    id: "channel-left",
    kind: "channel",
    name: "Straight channel",
    x: 280,
    y: 304,
    width: 56,
    height: 336,
    rotation: 90,
    cables: 4,
  },
  {
    id: "channel-middle",
    kind: "channel",
    name: "Straight channel",
    x: 336,
    y: 584,
    width: 504,
    height: 56,
    rotation: 0,
    cables: 5,
  },
  {
    id: "channel-bottom",
    kind: "channel",
    name: "Straight channel",
    x: 840,
    y: 584,
    width: 448,
    height: 56,
    rotation: 0,
    cables: 5,
  },
  {
    id: "channel-right",
    kind: "channel",
    name: "Straight channel",
    x: 1288,
    y: 304,
    width: 56,
    height: 336,
    rotation: 90,
    cables: 5,
  },
  {
    id: "holder-left",
    kind: "holder",
    name: "Mini PC holder",
    x: 400,
    y: 664,
    width: 150,
    height: 86,
    rotation: 0,
  },
  {
    id: "holder-right",
    kind: "holder",
    name: "USB hub holder",
    x: 1048,
    y: 664,
    width: 150,
    height: 86,
    rotation: 0,
  },
];

export const INITIAL_ROUTES: CableRoute[] = [
  {
    id: "route-power",
    name: "PC power",
    color: "#56d7e4",
    diameter: 7,
    points: [
      [690, 252],
      [690, 360],
      [1316, 360],
      [1316, 612],
      [1086, 612],
    ],
  },
  {
    id: "route-display",
    name: "DisplayPort",
    color: "#5294ff",
    diameter: 6,
    points: [
      [912, 252],
      [912, 412],
      [1308, 412],
      [1308, 624],
      [730, 624],
    ],
  },
  {
    id: "route-usb",
    name: "USB hub",
    color: "#ffb020",
    diameter: 4,
    points: [
      [640, 252],
      [640, 388],
      [308, 388],
      [308, 612],
      [474, 612],
    ],
  },
];

